name: lint_python
on:
  push:
    paths:
      - bin/cloudflare_ips_reload.py
      - .github/workflows/lint_python.yml
  pull_request:
    paths:
    - bin/cloudflare_ips_reload.py
    - .github/workflows/lint_python.yml
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install black codespell mypy pytest ruff safety
      - run: ruff --output-format=github --line-length=100 bin/cloudflare_ips_reload.py
      - run: black --check . || true
      - run: codespell --skip="./.git/*"
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: mkdir -p /etc/nginx
      - run: python bin/cloudflare_ips_reload.py --help
